export const deportes = [
    "Ajedrez",
    "Atletismo",
    "Automovilismo",
    "Bádminton",
    "Baloncesto",
    "Balonmano",
    "Billar",
    "Boliche",
    "Boxeo",
    "Buceo",
    "Canotaje",
    "Ciclismo",
    "Cricket",
    "Escalada",
    "Esgrima",
    "Esquí",
    "Fútbol",
    "Fútbol americano",
    "Golf",
    "Hípica",
    "Judo",
    "Karate",
    "Levantamiento de pesas",
    "Lucha libre",
    "Natación",
    "Patinaje artístico",
    "Patinaje sobre hielo",
    "Patinaje sobre ruedas",
    "Paracaidismo",
    "Piragüismo",
    "Polo",
    "Rugby",
    "Snowboard",
    "Surf",
    "Taekwondo",
    "Tenis",
    "Tenis de mesa",
    "Tiro con arco",
    "Tiro deportivo",
    "Triatlón",
    "Voleibol"
];
